import { stringify as yamlStringify } from 'yaml';

import type { MountDecl, Template } from '../templates/schema.js';

const GENERATED_HEADER = `# Generated by buckle <https://github.com/buckle-dev/buckle>.
# Edit your template, not this file.
# This is a starting point for compose-based devcontainers.`;

type ComposeVolume =
  | string
  | {
      type?: string;
      source?: string;
      target: string;
      read_only?: boolean;
      consistency?: string;
    };

/**
 * Convert a buckle MountDecl into a compose volume entry.
 * We prefer long-form objects when we have readOnly/consistency so the
 * semantics survive round-tripping.
 */
function mountToComposeVolume(m: MountDecl, defaultConsistency?: string): ComposeVolume {
  const v: ComposeVolume = {
    type: m.type ?? 'bind',
    source: m.source,
    target: m.target,
  };
  if (m.readOnly) (v as { read_only?: boolean }).read_only = true;
  if (m.consistency || defaultConsistency) {
    (v as { consistency?: string }).consistency = m.consistency ?? defaultConsistency;
  }
  return v;
}

/**
 * Emit a docker-compose.yml when the template declares `compose:` and points at a missing file.
 *
 * Improvements over the original minimal emitter:
 * - Respects `workspaceFolder` (defaults to /workspaces)
 * - Converts `mounts` into proper volume entries (long form when needed)
 * - Better runArgs translation (more flags)
 * - Emits `working_dir` when workspaceFolder is known
 * - Deterministic output + clear generated header
 */
export function renderCompose(t: Template): string {
  if (!t.compose) throw new Error('renderCompose called without compose template');

  const service = t.compose.service;
  const workspaceFolder = t.workspaceFolder ?? '/workspaces';

  const node: Record<string, unknown> = {};

  if (t.image) node['image'] = t.image;

  if (t.build) {
    node['build'] = {
      context: t.build.context ?? '..',
      dockerfile: t.build.dockerfile,
      ...(t.build.args ? { args: t.build.args } : {}),
      ...(t.build.target ? { target: t.build.target } : {}),
    };
  }

  if (t.runArgs && t.runArgs.length > 0) {
    const cap: string[] = [];
    const securityOpt: string[] = [];

    for (const arg of t.runArgs) {
      if (arg.startsWith('--cap-add=')) cap.push(arg.slice('--cap-add='.length));
      else if (arg === '--privileged') node['privileged'] = true;
      else if (arg === '--init') node['init'] = true;
      else if (arg.startsWith('--security-opt=')) securityOpt.push(arg.slice('--security-opt='.length));
    }

    if (cap.length > 0) node['cap_add'] = cap;
    if (securityOpt.length > 0) node['security_opt'] = securityOpt;
  }

  if (t.env && Object.keys(t.env).length > 0) {
    // Sort for stable output
    const sorted: Record<string, string> = {};
    for (const k of Object.keys(t.env).sort()) sorted[k] = t.env[k]!;
    node['environment'] = sorted;
  }

  if (t.forwardPorts && t.forwardPorts.length > 0) {
    node['ports'] = t.forwardPorts.map((p) => (typeof p === 'number' ? `${p}:${p}` : `${p.port}:${p.port}`));
  }

  // Workspace volume + user mounts
  const volumes: ComposeVolume[] = [];

  // Primary workspace bind (cached is a common Docker Desktop optimization)
  volumes.push({
    type: 'bind',
    source: '..',
    target: workspaceFolder,
    consistency: 'cached',
  });

  if (t.mounts && t.mounts.length > 0) {
    // Dedupe by target (later wins, same as devcontainer generator)
    const byTarget = new Map<string, MountDecl>();
    for (const m of t.mounts) byTarget.set(m.target, m);

    for (const m of byTarget.values()) {
      volumes.push(mountToComposeVolume(m));
    }
  }

  if (volumes.length > 0) node['volumes'] = volumes;

  if (t.remoteUser || t.containerUser) {
    node['user'] = t.remoteUser ?? t.containerUser;
  }

  node['working_dir'] = workspaceFolder;
  node['command'] = 'sleep infinity';

  const doc = {
    services: { [service]: node },
  };

  const yaml = yamlStringify(doc);
  return `${GENERATED_HEADER}\n\n${yaml}`;
}
