import type { Template } from '../templates/schema.js';

/**
 * Render a minimal Dockerfile when a template uses `build:` but the user hasn't already supplied
 * one. We only generate one if `build.dockerfile` resolves to a path that doesn't exist (the
 * writer checks). This emitter produces a sensible starting point.
 */
export function renderDockerfile(t: Template, fromImage: string): string {
  const lines: string[] = [
    `# Generated by buckle. Customize as needed; this is a starting point.`,
    `FROM ${fromImage}`,
  ];
  // Surface the chosen target / args as comments so users learn the affordances.
  if (t.build?.target) {
    lines.push(`# Multi-stage build target: ${t.build.target}`);
  }
  if (t.build?.args) {
    for (const [k, v] of Object.entries(t.build.args)) {
      lines.push(`ARG ${k}=${v}`);
    }
  }
  lines.push(``);
  lines.push(`# Default user / shell.`);
  lines.push(`USER ${t.remoteUser ?? 'vscode'}`);
  lines.push(``);
  return lines.join('\n');
}
