/** `buckle up [<template>]` — render (if missing), build, up, exec bash. */
import { join } from 'node:path';

import { Driver } from '../../docker/driver.js';
import { exists, readTextOrUndefined } from '../../util/fs.js';
import { BuckleError, ErrorCode } from '../../util/errors.js';
import type { CliContext } from '../context.js';
import { emit, jsonOk } from '../json-out.js';
import { renderTemplate } from '../render.js';

export interface UpArgs {
  template?: string;
}

export async function runUp(ctx: CliContext, args: UpArgs): Promise<number> {
  const dcDir = join(ctx.cwd, '.devcontainer');
  const dcJson = join(dcDir, 'devcontainer.json');
  let templateName = args.template;
  if (!(await exists(dcJson))) {
    if (!templateName) {
      // This path should now be almost unreachable because dispatch() routes
      // `buckle up` (no template, no dc) to the TUI with up-intent.
      // We keep a clear error as a safety net for unusual invocation paths.
      throw new BuckleError(
        ErrorCode.E_TEMPLATE_NOT_FOUND,
        'no .devcontainer/devcontainer.json in this folder',
        'pass a template name (e.g. `buckle up node`) or run `buckle up` with no arguments to use the interactive wizard',
      );
    }
    await renderTemplate(ctx, {
      templateName,
      features: ctx.flags.feature ?? [],
      ...(ctx.flags.trust !== undefined ? { trust: ctx.flags.trust } : {}),
      yes: true,
    });
  } else if (templateName) {
    // Re-render only if the user explicitly passed a template.
    await renderTemplate(ctx, {
      templateName,
      features: ctx.flags.feature ?? [],
      ...(ctx.flags.trust !== undefined ? { trust: ctx.flags.trust } : {}),
      yes: true,
    });
  } else {
    templateName = 'unknown';
    // Helpful note when dogfooding / iterating on templates: plain `buckle up` reuses
    // whatever .devcontainer/devcontainer.json is already on disk.
    const dcText = await readTextOrUndefined(dcJson);
    if (dcText && dcText.includes('Generated by buckle')) {
      ctx.logger.info('using existing .devcontainer/ (pass a template name, e.g. `buckle up ai-native`, to refresh from current templates)');
    }
  }

  const driver = new Driver({
    workspaceFolder: ctx.cwd,
    templateName: templateName ?? 'unknown',
    logger: ctx.logger,
  });
  const result = await driver.up({
    ...(ctx.flags.rebuild ? { rebuild: true } : {}),
    ...(ctx.flags.json ? { quiet: true } : {}),
  });
  ctx.logger.success(`container up: ${result.containerName}`);

  if (!ctx.flags.detach) {
    const exit = await driver.bash({ ...(ctx.flags.user ? { user: ctx.flags.user } : {}) });
    if (ctx.flags.json) {
      emit(jsonOk({ container: result, exitCode: exit.exitCode }, ctx.cwd));
    }
    return exit.exitCode;
  }
  if (ctx.flags.json) emit(jsonOk({ container: result }, ctx.cwd));
  return 0;
}
