import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';

import { runView } from '../../src/cli/commands/view.js';
import { makeContext } from '../../src/cli/context.js';

beforeEach(() => {
  vi.spyOn(process.stdout, 'write').mockImplementation(() => true);
});
afterEach(() => {
  vi.restoreAllMocks();
});

describe('runView', () => {
  it('prints isolated devcontainer json for a builtin', async () => {
    const ctx = makeContext({}, '/tmp/view-proj');
    const code = await runView(ctx, { template: 'node' });
    expect(code).toBe(0);
    const out = (process.stdout.write as unknown as { mock: { calls: [string][] } }).mock.calls
      .flat()
      .join('');
    expect(out).toContain('Generated by buckle');
    expect(out).toContain('"buckle.isolate": true');
  });

  it('emits json envelope and applies --feature overlay', async () => {
    const ctx = makeContext({ json: true, feature: ['dod'] }, '/tmp/view-proj');
    const code = await runView(ctx, { template: 'ubuntu-base' });
    expect(code).toBe(0);
    const out = (process.stdout.write as unknown as { mock: { calls: [string][] } }).mock.calls
      .flat()
      .join('');
    expect(out).toMatch(/"ok":\s*true/);
    expect(out).toContain('docker.sock');
  });

  it('share-home keeps host grok mounts', async () => {
    const ctx = makeContext({ isolate: false, shareHome: true }, '/tmp/view-proj');
    await runView(ctx, { template: 'claude-corp' });
    const out = (process.stdout.write as unknown as { mock: { calls: [string][] } }).mock.calls
      .flat()
      .join('');
    expect(out).toContain('${localEnv:HOME}/.grok');
    expect(out).toContain('"buckle.isolate": false');
  });
});
