import { describe, expect, it } from 'vitest';

import { renderCompose } from '../../src/generators/compose.js';
import type { Template } from '../../src/templates/schema.js';

describe('renderCompose', () => {
  it('throws if compose is missing', () => {
    const t: Template = { version: '0.1.0', image: 'foo:1' };
    expect(() => renderCompose(t)).toThrow();
  });

  it('emits a service entry with image + workspace volume', () => {
    const t: Template = {
      version: '0.1.0',
      image: 'foo:1',
      compose: { file: 'docker-compose.yml', service: 'app' },
    };
    const out = renderCompose(t);
    expect(out).toContain('services:');
    expect(out).toContain('app:');
    expect(out).toContain('image: foo:1');
    expect(out).toContain('command: sleep infinity');
  });

  it('maps cap_add and privileged from runArgs', () => {
    const t: Template = {
      version: '0.1.0',
      image: 'foo:1',
      compose: { file: 'docker-compose.yml', service: 'app' },
      runArgs: ['--cap-add=SYS_PTRACE', '--privileged'],
    };
    const out = renderCompose(t);
    expect(out).toContain('SYS_PTRACE');
    expect(out).toContain('privileged: true');
  });

  it('maps forwardPorts to compose port mappings', () => {
    const t: Template = {
      version: '0.1.0',
      image: 'foo:1',
      compose: { file: 'docker-compose.yml', service: 'app' },
      forwardPorts: [3000, { port: 8080 }],
    };
    const out = renderCompose(t);
    expect(out).toContain('3000:3000');
    expect(out).toContain('8080:8080');
  });

  it('emits build node when build is present', () => {
    const t: Template = {
      version: '0.1.0',
      build: { dockerfile: 'Dockerfile', context: '.' },
      compose: { file: 'docker-compose.yml', service: 'app' },
    };
    const out = renderCompose(t);
    expect(out).toContain('build:');
    expect(out).toContain('dockerfile: Dockerfile');
  });

  it('respects workspaceFolder and converts mounts to volume objects', () => {
    const t: Template = {
      version: '0.1.0',
      image: 'foo:1',
      compose: { file: 'docker-compose.yml', service: 'app' },
      workspaceFolder: '/work',
      mounts: [
        { source: '${localEnv:HOME}/.aws', target: '/home/vscode/.aws', type: 'bind', readOnly: true },
        { source: '/tmp/data', target: '/data', type: 'bind' },
      ],
    };
    const out = renderCompose(t);
    expect(out).toContain('working_dir: /work');
    expect(out).toContain('source: ${localEnv:HOME}/.aws');
    expect(out).toContain('read_only: true');
    expect(out).toContain('/data');
  });

  it('includes a generated header comment', () => {
    const t: Template = {
      version: '0.1.0',
      image: 'foo:1',
      compose: { file: 'docker-compose.yml', service: 'app' },
    };
    const out = renderCompose(t);
    expect(out.startsWith('# Generated by buckle')).toBe(true);
  });
});
