import { describe, expect, it } from 'vitest';

import { buildDevcontainer, serializeDevcontainer } from '../../src/generators/devcontainer.js';
import type { Template } from '../../src/templates/schema.js';

describe('buildDevcontainer', () => {
  it('emits image source', () => {
    const t: Template = { version: '0.1.0', image: 'mcr.io/x:1' };
    const dc = buildDevcontainer(t, 'proj');
    expect(dc.image).toBe('mcr.io/x:1');
    expect(dc.build).toBeUndefined();
    expect(dc.dockerComposeFile).toBeUndefined();
  });

  it('emits build source', () => {
    const t: Template = {
      version: '0.1.0',
      build: { dockerfile: 'Dockerfile', context: '.', args: { X: '1' } },
    };
    const dc = buildDevcontainer(t, 'proj');
    expect(dc.build).toEqual({ dockerfile: 'Dockerfile', context: '.', args: { X: '1' } });
  });

  it('emits compose source', () => {
    const t: Template = {
      version: '0.1.0',
      compose: { file: 'docker-compose.yml', service: 'app', runServices: ['app', 'db'] },
    };
    const dc = buildDevcontainer(t, 'proj');
    expect(dc.dockerComposeFile).toBe('docker-compose.yml');
    expect(dc.service).toBe('app');
    expect(dc.runServices).toEqual(['app', 'db']);
  });

  it('compiles convenience features into native features', () => {
    const t: Template = {
      version: '0.1.0',
      image: 'foo:1',
      features: ['gh', 'node:20'],
    };
    const dc = buildDevcontainer(t, 'proj');
    expect(dc.features).toMatchObject({
      'ghcr.io/devcontainers/features/github-cli:1': {},
      'ghcr.io/devcontainers/features/node:1': { version: '20' },
    });
  });

  it('serializes mounts as long-syntax strings', () => {
    const t: Template = {
      version: '0.1.0',
      image: 'foo:1',
      mounts: [
        { source: '/a', target: '/b', type: 'bind', readOnly: true },
        { source: 'vol', target: '/c', type: 'volume' },
      ],
    };
    const dc = buildDevcontainer(t, 'proj');
    expect(dc.mounts).toEqual([
      'source=/a,target=/b,type=bind,readonly',
      'source=vol,target=/c,type=volume',
    ]);
  });

  it('rolls lifecycle hooks into the spec keys', () => {
    const t: Template = {
      version: '0.1.0',
      image: 'foo:1',
      lifecycle: {
        postCreate: ['echo a'],
        postStart: ['echo b'],
      },
    };
    const dc = buildDevcontainer(t, 'proj');
    expect(dc.postCreateCommand).toEqual('echo a');
    expect(dc.postStartCommand).toEqual('echo b');
  });

  it('serializes deterministically with a banner', () => {
    const t: Template = { version: '0.1.0', image: 'foo:1' };
    const out = serializeDevcontainer(buildDevcontainer(t, 'proj'));
    expect(out.startsWith('// Generated by buckle')).toBe(true);
    // Sanity: keys are sorted alphabetically; image precedes name should be false → name precedes image alpha.
    const json = JSON.parse(out.replace(/^\/\/.+\n/, ''));
    expect(json.image).toBe('foo:1');
  });
});
